GET http://localhost:3000/todo

###

GET http://localhost:3000/todo/single/697b2dd3baee3ef3bf0aacdb

###

POST http://localhost:3000/todo/todo
Content-Type: application/json

{
    "title": "Sixth task",
    "description": "This is my sixth task."
}

###

PATCH http://localhost:3000/todo/697b2dd3baee3ef3bf0aacdb
Content-Type: application/json

{
    "isDone": "invalid"
}

###

DELETE  http://localhost:3000/todo/697b2dd3baee3ef3bf0aacdb

###

POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullName": "Falade Joseph",
    "email": "faladejoseph700@gmail.com",
    "password": "whatever"
}