GET http://localhost:3000/todo

###

GET http://localhost:3000/todo/single/697b2dd3baee3ef3bf0aacdb

###

POST http://localhost:3000/todo/todo
Content-Type: application/json

{
    "title": "Sixth task",
    "description": "This is my sixth task."
}

###

PATCH http://localhost:3000/todo/697b2dd3baee3ef3bf0aacdb
Content-Type: application/json

{
    "isDone": "invalid"
}

###

DELETE  http://localhost:3000/todo/697b2dd3baee3ef3bf0aacdb

###

POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullName": "Falade Joseph",
    "email": "faladejoseph700@gmail.com",
    "password": "whatever"
}

###
PATCH http://localhost:3000/auth/verify
Content-Type: application/json

{
    "otp": "1112",
    "otpToken": "15f9aa7d-511b-4b58-a2fa-fa4885dbe528",
    "purpose": "verify-email"
}

//"message": "User created successfully.",
//"otpToken": "15f9aa7d-511b-4b58-a2fa-fa4885dbe528",
//"purpose": "verify-email"